# Generated by Django 3.2.6 on 2021-09-01 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClubSociety',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('slogan', models.CharField(max_length=150)),
                ('description', models.CharField(max_length=600)),
                ('logo', models.ImageField(upload_to='Uploads/Logos'))
            ],
        ),
    ]
