# Generated by Django 3.2.6 on 2021-09-01 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clubsociety',
            name='price',
            field=models.IntegerField(default=0),
        )
    ]
