# Generated by Django 3.2.6 on 2021-09-01 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_clubsociety_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='clubsociety',
            name='President',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
