# Generated by Django 3.2.6 on 2021-09-01 19:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_auto_20210901_2334'),
    ]

    operations = [
        migrations.AddField(
            model_name='clubsociety',
            name='categoryId',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='store.category'),
        ),
    ]
