# Generated by Django 3.2.6 on 2021-09-04 04:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_members'),
    ]

    operations = [
        migrations.RenameField(
            model_name='members',
            old_name='secondname',
            new_name='lastname',
        ),
    ]
