# Generated by Django 3.2.6 on 2021-10-07 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_rename_secondname_members_lastname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='members',
            name='firstname',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='members',
            name='lastname',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='members',
            name='mobile',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='members',
            name='password',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
