# Generated by Django 4.1.3 on 2022-12-06 12:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("space", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="previousyearquestions",
            name="semester",
        ),
        migrations.RemoveField(
            model_name="previousyearquestions",
            name="subject",
        ),
        migrations.AddField(
            model_name="branch",
            name="semester",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="space.semester",
            ),
        ),
        migrations.AddField(
            model_name="semester",
            name="subjects",
            field=models.ForeignKey(
                default=0,
                on_delete=django.db.models.deletion.CASCADE,
                to="space.subjects",
            ),
            preserve_default=False,
        ),
    ]
