# Generated by Django 4.1.3 on 2022-12-13 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('space', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paper',
            name='paper_pdf',
            field=models.FileField(default=None, null=True, upload_to='paper/'),
        ),
    ]
