# Generated by Django 4.1.3 on 2022-12-06 12:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("space", "0002_remove_previousyearquestions_semester_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="semester",
            name="subjects",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="space.subjects",
            ),
        ),
    ]
