# Generated by Django 4.1.3 on 2022-12-06 12:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("space", "0004_remove_semester_subjects_subjects_semester"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="branch",
            name="semester",
        ),
        migrations.AddField(
            model_name="semester",
            name="branch",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="space.branch",
            ),
        ),
    ]
