# Generated by Django 4.1.3 on 2023-09-14 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('space', '0004_semester_jobsmodel_position_subjects_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClubMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('registration_id', models.CharField(max_length=255)),
                ('department', models.CharField(max_length=255)),
                ('availability', models.CharField(max_length=255)),
                ('level_of_interest', models.CharField(max_length=255)),
                ('reason_to_select', models.CharField(max_length=255)),
            ],
        ),
    ]
