# Generated by Django 4.1.3 on 2022-12-06 12:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("space", "0005_remove_branch_semester_semester_branch"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="semester",
            name="branch",
        ),
        migrations.AddField(
            model_name="branch",
            name="semester",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="space.semester",
            ),
        ),
        migrations.CreateModel(
            name="Notes",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "pdf_file",
                    models.FileField(
                        upload_to="uploads/notes/<django.db.models.fields.related.ForeignKey>/<django.db.models.fields.related.ForeignKey>"
                    ),
                ),
                (
                    "branch_name",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="space.branch",
                    ),
                ),
                (
                    "semester",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="space.semester",
                    ),
                ),
            ],
        ),
    ]
