# Generated by Django 4.1.3 on 2022-12-06 13:12

from django.db import migrations, models
import space.utils


class Migration(migrations.Migration):

    dependencies = [
        ("space", "0006_remove_semester_branch_branch_semester_notes"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="branch",
            name="semester",
        ),
        migrations.AlterField(
            model_name="notes",
            name="pdf_file",
            field=models.FileField(upload_to=space.utils.NotesPath),
        ),
        migrations.AddField(
            model_name="branch",
            name="semester",
            field=models.ManyToManyField(to="space.semester"),
        ),
    ]
