# Generated by Django 4.1.3 on 2022-12-11 17:25

from django.db import migrations, models
import space.utils


class Migration(migrations.Migration):

    dependencies = [
        ('space', '0009_alter_branch_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline', models.CharField(max_length=30)),
                ('dp_image', models.ImageField(upload_to=space.utils.ArticlePath)),
                ('update_txt', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='PreviousYearQuestions',
        ),
    ]
