# Generated by Django 4.1.3 on 2022-12-12 06:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("space", "0009_alter_branch_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="previousyearquestions",
            name="semester",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="space.semester",
            ),
        ),
        migrations.AddField(
            model_name="previousyearquestions",
            name="year",
            field=models.IntegerField(default=2020),
        ),
        migrations.AlterField(
            model_name="previousyearquestions",
            name="branch_name",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="space.branch",
            ),
        ),
    ]
