# Generated by Django 4.1.3 on 2022-12-12 06:43

from django.db import migrations, models
import space.utils


class Migration(migrations.Migration):

    dependencies = [
        ("space", "0010_previousyearquestions_semester_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="previousyearquestions",
            name="pdf_file",
            field=models.FileField(null=True, upload_to=space.utils.PyqPath),
        ),
    ]
